### ISSUE TITLE
angular.equals(queryJson,{}) is giving me an incorrect 'true'

### ISSUE THREAD

**Issue by nmorse** [pkozlowski-opensource/angularjs-mongolab#13]
When passing in what seems to be a perfectly good object for `queryJson` such as 

```
{"$or":[
    {"attrib1": {"$regex":"some", "$options":"i"}},
    {"attrib2": {"$regex":"", "$options":"i"}}
    ]
}
```

into `preparyQueryParam()` , but when this runs...

```
angular.equals(queryJson,{}) // fragment of line 37 of mongolabResourceHttp.js
```

I (incorrectly) get `true` :8ball: 

I looked into this and it **_may**_ have to do with a bug in angular when an object has an undefined value `{"test":undefined}` or it may have something to do with the dollar sign `$keys` needed for mongodb, I am not sure.

I am working on a fix...

**Comment by pkozlowski-opensource** [comment]
Ah, you are right, the problem is that `angular.equals` will ignore all the properties starting with `$` :-/ So the proper way of doing things would be check if a given object got any keys defined.
