### ISSUE TITLE
Getting success callbacks on success AND errors.

### ISSUE THREAD

**Issue by alangrus** [pkozlowski-opensource/angularjs-mongolab#16]
I have been having some success using this module to help streamline my database interactions, so far so good.

I am getting a query resource to read as expected. The managers object gets passed into my template $scope and the log shows a "read success" message - Good. 

In wanting to next deal with error conditions, I find that passing in a known bad ID still takes the same path to the successCB, the errorCB should fire but does not. Have I set this up wrong or made a wrong assumption?  Thanks.

```
.controller('ContactCtrl', function($scope, $rootScope, $log, ManagersCollection) {
  var criteriaObject = { im_id: "alang" };
  var sortObject = { sort: { _id: 1 } };
  var successCB  = function(managers) {
    $scope.manager = managers[0];  // use [0] for the first selected item.
    $log.log( "Managers ID " + criteriaObject.im_id + " read success" );
  };
  var errorCB = function(managers) {
    throw new Error(criteriaObject.im_id + ' item read went wrong...');
  };

  ManagersCollection.query(
    criteriaObject,
    sortObject,
    successCB,
    errorCB
  );
})
```

**Comment by pkozlowski-opensource** [comment]
@alangrus yes, I've let a bug slip in the code, sorry about this... I've fixed it in 4dc2e4350421cd5d140d4b39bdf29bfebf3cfbca but then decided to drop callbacks altogether in b16e63fc3e7486643097f4a0b286577c62b85aad as the promise-based API is much nicer to work with. 

A new version is pushed to Bower, I will be updating this repo (`gh-pages`) with a new release.
