### ISSUE TITLE
Is this only usefull/save for development

### ISSUE THREAD

**Issue by RBeek** [pkozlowski-opensource/angularjs-mongolab#18]
- Is there a scenario, that you can use this in production?
- To somehow not expose the api-key.

thanks

**Comment by pkozlowski-opensource** [comment]
@RBeek nope, it is not the goal of this helper lib to be used in production as-is. By default it is mostly useful for demos / publicly available data. You _can_ make it safer by hiding apiKey behind a proxy.

Anyway, this was discussed in details before:
https://github.com/pkozlowski-opensource/angularjs-mongolab-promise/issues/9
https://github.com/pkozlowski-opensource/angularjs-mongolab-promise/issues/10

so I'm going to close this one, but ready to discuss more here if needed.
