### ISSUE TITLE
brackets for api key

### ISSUE THREAD

**Issue by ghost** [pkozlowski-opensource/angularjs-mongolab#7]
included in your example for where you add the API-KEY:
app.constant('MONGOLAB_CONFIG',{API_KEY:'[your key goes here]', DB_NAME:'angularjs'});

The brackets around the api-key cause problems for me. Works fine once they're gone.

**Comment by ghost** [comment]
That's how you have it on Plunkr too, so maybe i'm just dull and didn't know that the bracket's aren't meant to be included. Thanks for writing this by the way, it's really really great!

**Comment by pkozlowski-opensource** [comment]
@timothybone Thnx for taking time to open this issue. I don't know why I'm keep using those bracket while indicating params to be supplied. Anyway, I agree that it might be confusing so changed it dd4000e5c830a33ce7c58723d35b998829d44560.

Glad that you are finding this little script useful.
